### ISSUE TITLE
Move Avalonia.Flexbox in this repository

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia.Labs#8]
[Avalonia.Flexbox](https://github.com/jp2masa/Avalonia.Flexbox)

**Comment by maxkatz6** [comment]
What is reason to move it?
It's not a toolkit repository, nor a repository for this party controls. It's a repository for unstable (API-wise) controls, some of which might be merged into the core at some point.

**Comment by maxkatz6** [comment]
cc @jp2masa

**Comment by jp2masa** [comment]
@maxkatz6 I can open a PR to move the code here, would it go to Avalonia.Labs.Controls or a new csproj?

**Comment by emmauss** [comment]
> Avalonia.Labs

A new project labelled Avalonia.Labs.Panels

**Comment by Mrxx99** [comment]
Can this also be considered: https://github.com/Nickelony/AvaloniaSpacedGrid
RowSpacing and ColumnSpacing would be great if could be added directly to Grid at some point. Like Spacing on StackPanel

**Comment by jp2masa** [comment]
@emmauss @maxkatz6 Sorry for taking so long to respond.

I'm almost ready to create a PR to discuss this better, just have one more question. In my repo, there are two classes for flex layout: a panel and a non-virtualizing layout (for items repeater). I know items repeater has some very hard to fix bugs, which led to moving it to a separate package. Should I bring the items repeater part as well? If so, should it be in a separate project to avoid bringing the extra dependency?

**Comment by maxkatz6** [comment]
It can be "Avalonia.Labs.Panels" project for ItemsControl panels, and "Avalonia.Labs.Layouts" for ItemsRepeater layouts.

But, honestly, I am not sure if adding ItemsRepeater layout is worth it, as it might not be supported for too long.
