### ISSUE TITLE
Tap Events: Holding event not firing.

### ISSUE THREAD

**Issue by GIL0487** [AvaloniaUI/Avalonia.Labs#85]
Good afternoon,

My system:
- Win 11 Enterprise 23H2
- VS2022 17.11.4
- Avalonia 11.1.0

I have created a very basic Avalonia application: this was done via the VS Project Menu -> Avalonia C# Project.
I added a button to the MainWidow.

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaApplication1">

	<Button Margin="50, 50, 0, 0"
            Content="TEST"
            Height="50"
            Width="50"
            Background="Yellow"
            Foreground="Red"
            HorizontalAlignment="Left"
            VerticalAlignment="Top"
            Gestures.IsHoldWithMouseEnabled="True"
            Gestures.IsHoldingEnabled="True"
            Holding="InputElement_OnHolding">
    </Button>

</Window>
```

In the code behind, I implemented InputElement_OnHolding as follow, with an active break point on the only instruction

```
using Avalonia.Controls;
using Avalonia.Input;

namespace AvaloniaApplication1.Views;

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }

    private void InputElement_OnHolding(object? sender, HoldingRoutedEventArgs e)
    {
        var breakPointTest = false;
    }
}
```

The breakpoint in never hit and, by looking ad the DevTools, the holding event is never generated by the Avalonia code.

Am I doing something wrong? Is there any other way for the Holding event to be generated?

Based on the online documentation, settings the Gestures should be enough.
https://docs.avaloniaui.net/docs/concepts/input/pointer

Thanks

**Comment by emmauss** [comment]
This isn't the place to report issues with Avalonia itself. Update and test with the latest avalonia stable and beta, and if the issue persists, open an issue here. https://github.com/AvaloniaUI/Avalonia

**Comment by GIL0487** [comment]
Apologies, I will try that and report. Thanks
